debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[docker]
domain = "docker.local"
watch = true

[api]
  [api.statistics]
    recentErrors = 10
